### PR TITLE
docs: improve `PredictTextSentimentAnalysisSample`

### LINKED ISSUE #1097: docs: `PredictTextSentimentAnalysisSample` uses unsafe JSON serialization strategy
# Description

The [PredictTextSentimentAnalysisSample](https://github.com/googleapis/java-aiplatform/blob/HEAD/samples/snippets/src/main/java/aiplatform/PredictTextSentimentAnalysisSample.java) Java code sample used in documentation [here](https://cloud.google.com/vertex-ai/docs/samples/aiplatform-predict-text-sentiment-analysis-sample) has a flaw as is.

If passed an input containing the `"` character like `how much for 24"x24" pizza boxes` it throws an error:
```text
Exception in thread "main" com.google.protobuf.InvalidProtocolBufferException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 49 path $.content
	at com.google.protobuf.util.JsonFormat$ParserImpl.merge(JsonFormat.java:1347)
	at com.google.protobuf.util.JsonFormat$Parser.merge(JsonFormat.java:477)
	at aiplatform.PredictTextSentimentAnalysisSample.predictTextSentimentAnalysis(PredictTextSentimentAnalysisSample.java:61)
	at aiplatform.PredictTextSentimentAnalysisSample.main(PredictTextSentimentAnalysisSample.java:39)
```

This can be resolved if the input is properly serialized using `com.google.gson` which is already included in the sample's dependencies.

### PR DESCRIPTION
**Pull request by wallind**
# Description

Updates a code sample to have safe serialization of input which may come unsanitized. 

# Github Ticket(s)
Fixes #1097  ☕️

# Checklist
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-aiplatform/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Comment by wallind** [comment]
I thought about adding a test case for an input with `"`. Would that be worth it? I opted not to for my inital draft. lemme know.

**Comment by kurtisvg** [comment]
Tagging @Sita04 for initial review.

**Review by Sita04 — APPROVED** [review]
Thanks for the changes. LGTM.

@kurtisvg Back to you again for the final review.

**Review by kurtisvg — APPROVED** [review]

**Comment by wallind** [comment]
@kurtisvg is this waiting on anything to move forward? *following up here as it's been on my `TODO:` list to get this closed

**Comment by kurtisvg** [comment]
Looks like it's approved by the language reviewer (me + @Sita04) and just needs to be approved by a product reviewer (@googleapis/cdpe-cloudai)

**Review by balajismaniam — APPROVED** [review]
LGTM.

**Comment by kweinmeister** [comment]
Thank you for your contribution, and apologies for the delay in getting this merged @wallind.

We have actually migrated all of our Java samples to a centralized repo https://github.com/GoogleCloudPlatform/java-docs-samples, and will be deleting the samples here.

We can review and merge if you'd like to submit the PR there. Thanks again!

**Comment by wallind** [comment]
> Thank you for your contribution, and apologies for the delay in getting this merged @wallind.
> 
> We have actually migrated all of our Java samples to a centralized repo https://github.com/GoogleCloudPlatform/java-docs-samples, and will be deleting the samples here.
> 
> We can review and merge if you'd like to submit the PR there. Thanks again!

no problem. and done https://github.com/GoogleCloudPlatform/java-docs-samples/pull/7562! can't wait to get this change added 😁

**Comment by wallind** [comment]
superseded by PR in the new repo https://github.com/GoogleCloudPlatform/java-docs-samples/pull/7562

**Pull request closed without merging**
